network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      addresses:
        - 192.168.1.250/24
      gateway4: 192.168.1.1
      nameservers:
          addresses: [1.1.1.1, 8.8.8.8]
