network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      addresses: ["192.168.1.250/24"]
      nameservers:
          addresses: ["1.1.1.1", "1.0.0.1"]
      routes:
        - to: default
          via: 192.168.1.1
