---
collections:
  - name: community.general
    version: 2.5.0
    source: https://galaxy.ansible.com
  - name: community.docker
    version: 1.5.0
    source: https://galaxy.ansible.com
  - name: ansible.posix
    version: 1.2.1-dev4
    source: https://galaxy.ansible.com
