---
roles:
  # https://galaxy.ansible.com/geerlingguy/docker
  # https://github.com/geerlingguy/ansible-role-docker
  - src: geerlingguy.docker
    version: 4.2.3


  # https://galaxy.ansible.com/geerlingguy/node_exporter
  # https://github.com/geerlingguy/ansible-role-node_exporter
  - src: geerlingguy.node_exporter
    version: 1.0.2
