---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: apt cleanup cron file under /etc/cron.d
      ansible.builtin.cron:
        name: apt cleanup cronjob
        special_time: "monthly"
        user: root
        job: "/usr/local/bin/apt-clean-uninstalled"
        cron_file: apt-clean-job
        state: present

