---
- name: Torrent Service
  hosts: torrent_server
  become: true
  become_user: root
  tasks:
    # - name: Add qbittorrent repository from PPA
    #   ansible.builtin.apt_repository:
    #     repo: 'ppa:qbittorrent-team/qbittorrent-stable'
    #     filename: qbittorrent
    #     state: present
    #     update_cache: yes
    - name: Install qbittorrent
      ansible.builtin.apt:
        name: qbittorrent-nox
        state: present
      notify:
        - Qbittorrent service
    - name: Ensure qbittorrent service file
      ansible.builtin.copy:
        src: ./files/etc/systemd/system/qbittorrent-nox.service
        dest: /etc/systemd/system/qbittorrent-nox.service
        owner: root
        group: root
        mode: '0644'
      notify:
        - Qbittorrent service


  handlers:
    - name: Qbittorrent service
      ansible.builtin.systemd:
        name: qbittorrent-nox
        state: restarted
        enabled: true
