---
- name: Docker Installation
  hosts: pi4
  become: true
  become_user: root
  tasks:
    - name: Create /etc/apt/keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Docker keyring and repo
      block:
        # curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        - name: Keyring
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            keyring: /etc/apt/keyrings/docker.gpg
        - name: Repo
          ansible.builtin.apt_repository:
            repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            filename: docker
            state: present

    - name: Docker packages
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 0
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: Ensure "ubuntu" user belongs to "docker" group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: true

    - name: Ensure /etc/docker directory exists
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Docker daemon.json
      ansible.builtin.copy:
        src: ./files/etc/docker/daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0644'

    - name: Enable docker.service
      ansible.builtin.systemd:
        name: docker.service
        state: restarted
        enabled: true

    - name: Enable containerd.service
      ansible.builtin.systemd:
        name: containerd.service
        state: restarted
        enabled: true
