- hosts: pi4
  become: true
  vars:
    docker_users: [ "ubuntu" ]
    docker_install_compose: false
    docker_apt_arch: arm64
  roles:
    - geerlingguy.docker
  tasks:
    - name: Install docker python
      apt:
        pkg:
        - python3-docker
