---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install a .deb package from the internet
      apt:
        deb: https://github.com/muesli/duf/releases/download/v0.6.2/duf_0.6.2_linux_arm64.deb
