---
- hosts: 127.0.0.1
  become: true
  become_user: root
  tasks:
    - name: Update dnf cache
      ansible.builtin.dnf:
        update_cache: yes

    - name: Install packages
      ansible.builtin.dnf:
        state: latest
        install_weak_deps: yes
        name:
          - '@Development tools'
          - git
          - sqlite
          - gcc
          - gcc-c++
          - strace
          - gdb
          - make
          - automake
          - make
          - binutils-devel
          - glibc
          - glibc-common
          - glibc-devel
          - glibc-static
          - glibc-headers
          - strace
          - vim-common
          - vim-enhanced
          - nano

          - atop
          - iftop
          - iotop
          - nmon
          - procps-ng

          - meld
          - gitg
          - gitk
          - gnome-tweak-tool
          - gnome-shell-extension-user-theme
          - gnome-usage
          - gtk-murrine-engine
          - gtk-unico-engine
          - gtk2-engines
          - pavucontrol

          - java-1.8.0-openjdk
          - java-1.8.0-openjdk-devel
          - java-1.8.0-openjdk-headless
          - java-1.8.0-openjdk-javadoc
          - java-1.8.0-openjdk-javadoc-zip
          - java-1.8.0-openjdk-src
          - java-11-openjdk
          - java-11-openjdk-devel
          - java-11-openjdk-headless
          - java-11-openjdk-javadoc
          - java-11-openjdk-javadoc-zip
          - java-11-openjdk-jmods
          - java-11-openjdk-src
          - java-11-openjdk-static-libs
          - java-latest-openjdk
          - java-latest-openjdk-devel
          - java-latest-openjdk-headless
          - java-latest-openjdk-javadoc
          - java-latest-openjdk-javadoc-zip
          - java-latest-openjdk-jmods
          - java-latest-openjdk-src
          - java-latest-openjdk-static-libs

          - kernel-devel
          - kernel-headers
          - kernel-modules
          - kernel-modules-extra
