---
- name: Ensure each node hostfile
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Update the /etc/hosts file with node name
      ansible.builtin.lineinfile:
        dest: "/etc/hosts"
        regexp: ".*{{ hostvars[item]['ansible_hostname'] }}"
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}    {{ hostvars[item]['ansible_hostname'] }}"
        state: present
        backup: true
      with_items: "{{ groups['all'] }}"


# https://www.middlewareinventory.com/blog/ansible-update-etc-hosts-file-across-all-hosts/
