---
- name: Debug as root
  hosts: all
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  tasks:
    - name: Hostvars as root
      ansible.builtin.debug:
        var: hostvars
    - name: Ansible_env as root
      ansible.builtin.debug:
        var: ansible_env

- name: Debug as user
  hosts: all
  become: false
  tasks:
    - name: Hostvars as user
      ansible.builtin.debug:
        var: hostvars
    - name: Ansible_env as user
      ansible.builtin.debug:
        var: ansible_env
    - name: Groups
      ansible.builtin.debug:
        var: groups
