---
- name: Init
  hosts: all
  become: true
  become_user: root
  tasks:

#### append to /boot/firmware/config.txt
# [all]
# dtoverlay=disable-wifi
# dtoverlay=disable-bt

    - name: Create home config directory
      ansible.builtin.file:
        path: /home/ubuntu/.config
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0751'
    - name: Create home bin directory
      ansible.builtin.file:
        path: /home/ubuntu/bin
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0751'

    - name: Create htop config directory
      ansible.builtin.file:
        path: /home/ubuntu/.config/htop
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0700'
    - name: Ensure htop config
      ansible.builtin.copy:
        src: ./files/htop/htoprc
        dest: /home/ubuntu/.config/htop/htoprc
        owner: ubuntu
        group: ubuntu
        mode: '0664'

    - name: Copy ports script
      ansible.builtin.copy:
        src: ./files/bin/ports
        dest: /home/ubuntu/bin/ports
        owner: ubuntu
        group: ubuntu
        mode: '0751'

    - name: Copy thermals script
      ansible.builtin.copy:
        src: ./files/bin/thermals
        dest: /usr/local/bin/thermals
        owner: ubuntu
        group: ubuntu
        mode: '0751'

    - name: Ensure sshd config
      ansible.builtin.copy:
        src: ./files/etc/ssh/sshd_config.d/extras.conf
        dest: /etc/ssh/sshd_config.d/extras.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart sshd service

    # https://github.com/muesli/duf/releases
    - name: Install duf deb package
      ansible.builtin.apt:
        deb: https://github.com/muesli/duf/releases/download/v0.8.1/duf_0.8.1_linux_arm64.deb

    - name: Packages
      ansible.builtin.apt:
        pkg:
          - smartmontools
          - wget
          - curl
          - jq
          - git
          - build-essential
          - make
          - tree
          - iotop
          - linux-modules-extra-raspi
          - ca-certificates
          - gnupg
        state: present

  handlers:
    - name: Restart sshd service
      ansible.builtin.systemd:
        name: sshd
        state: restarted
