---
- name: Mount NFS pupa
  hosts: pi44
  become: true
  become_user: root
  tasks:
    - name: Install nfs-common
      ansible.builtin.apt:
        pkg:
          - nfs-common
        state: present

    - name: Create /disks directory if it does not exist
      ansible.builtin.file:
        path: /disks
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Mount the NFS volume
      ansible.posix.mount:
        src: 192.168.1.240:/volume1/pupa
        path: /disks/pupa
        opts: nfsvers=4,rw,nosuid,nodev,relatime,nofail,hard,_netdev,x-systemd.automount,x-systemd.device-timeout=10s
        state: mounted
        fstype: nfs
      notify:
        - Restart plex


  handlers:
    - name: Restart plex
      ansible.builtin.command:
        argv: ["docker", "compose", "restart"]
        chdir: /apps/plex
      changed_when: true
