---
- hosts: all
  roles:
    - cloudalchemy.node-exporter
  vars:
    node_exporter_version: 1.1.1
    node_exporter_enabled_collectors:
      - systemd
      - textfile:
          directory: "{{ node_exporter_textfile_dir }}"
      - filesystem:
          ignored-mount-points: "^/(sys|proc|dev)($|/)"
          ignored-fs-types: "^(sys|proc|auto)fs$"
      - tcpstat
      - mountstats
      #- perf
