---
- hosts: dhcp_server
  become: true
  become_user: root
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
        msg: "Reboot initiated"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
    - name: Enable dhcp server
      ansible.builtin.systemd:
        name: isc-dhcp-server.service
        state: started
        enabled: yes

- hosts: all:!dhcp_server
  become: true
  become_user: root
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
        msg: "Reboot initiated"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime