---
- hosts: localhost
  connection: local
  tasks:
    - ansible.builtin.debug:
        var: hostvars[inventory_hostname].ansible_user_id
    - name: Add a host in the configuration
      community.general.ssh_config:
        user: "{{ hostvars[inventory_hostname].ansible_user_id }}"
        host: "{{ item }}"
        hostname: "{{ hostvars[item].ansible_ssh_host }}"
        remote_user: ubuntu
        identity_file: "~/gitrepos/moukoublen/home-pies/keys/key"
        port: '22'
        state: present
      with_items: "{{ groups.all }}"
