---
- name: Init (root)
  hosts: all
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  tasks:

    - name: Ensure sshd config
      ansible.builtin.copy:
        src: ./files/etc/ssh/sshd_config.d/10-custom.conf
        dest: /etc/ssh/sshd_config.d/10-custom.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart sshd service

  handlers:
    - name: Restart sshd service
      ansible.builtin.systemd:
        name: sshd
        state: restarted
