---
- hosts: manager
  become: true
  tasks:
  - name: Initialize swarm manager
    command: |
      docker swarm init --advertise-addr "{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"

  - name: Get join token for worker
    command: docker swarm join-token -q worker
    register: worker_token
  - name: Get join token for manager
    command: docker swarm join-token -q manager
    register: manager_token

- hosts: nodes
  become: true
  tasks:
  - name: Run a command to join cluster
    shell: docker swarm join --token "{{ hostvars['manager']['worker_token'].stdout_lines | first }}" "{{ hostvars['manager']['ansible_ssh_host'] }}:2377"

