---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Update the /etc/hosts file with node name
      lineinfile:
        dest: "/etc/hosts"
        regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}"
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}\t{{ hostvars[item]['ansible_hostname'] }}"
        state: present
        backup: yes
      with_items: "{{groups['all']}}"


# https://www.middlewareinventory.com/blog/ansible-update-etc-hosts-file-across-all-hosts/
