#!/usr/bin/env bash


# sudo btrfs scrub:
#     -B                        do not background
#     -d                        stats per device (-B only)


__maint() {
  echo ''
  echo "$(date) - btrfs maintenance starts"

  echo ">> $(date --rfc-3339=seconds) start scrub to /storage/btrfs-ssd"
  btrfs scrub start -Bd /storage/btrfs-ssd
  echo ''

  echo ">> $(date --rfc-3339=seconds) start scrub to /storage/SleepyGary"
  btrfs scrub start -Bd /storage/SleepyGary
  echo ''


  echo ">> $(date --rfc-3339=seconds) start defrag to /storage/btrfs-ssd"
  btrfs filesystem defragment -r -f /storage/btrfs-ssd
  echo ''

  echo ">> $(date --rfc-3339=seconds) start defrag to /storage/SleepyGary"
  btrfs filesystem defragment -r -f /storage/SleepyGary
  echo ''

  echo "$(date) - btrfs maintenance ends"
  echo ''
}

__maint 2>&1 | tee /var/log/btrfs-maint.log
