#!/usr/bin/env bash

__maint() {
  echo ''
  echo "$(date) - btrfs maintenance starts"

  echo ">> $(date --rfc-3339=seconds) start scrub to /mainvol"
  btrfs scrub start -Bd /mainvol
  echo ''

  echo ">> $(date --rfc-3339=seconds) start scrub to /disks/zool"
  btrfs scrub start -Bd /disks/zool
  echo ''

  echo ">> $(date --rfc-3339=seconds) start scrub to /disks/SleepyGary"
  btrfs scrub start -Bd /disks/SleepyGary
  echo ''


  echo ">> $(date --rfc-3339=seconds) start defrag to /mainvol"
  btrfs filesystem defragment -r -f /mainvol
  echo ''

  echo ">> $(date --rfc-3339=seconds) start defrag to /disks/zool"
  btrfs filesystem defragment -r -f /disks/zool
  echo ''

  echo ">> $(date --rfc-3339=seconds) start defrag to /disks/SleepyGary"
  btrfs filesystem defragment -r -f /disks/SleepyGary
  echo ''

  echo "$(date) - btrfs maintenance ends"
  echo ''
}

__maint 2>&1 | tee /var/log/btrfs-maint.log
